/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PlacesLazyImport = createFileRoute('/places')()
const AffectationLazyImport = createFileRoute('/affectation')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PlacesLazyRoute = PlacesLazyImport.update({
  path: '/places',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/places.lazy').then((d) => d.Route))

const AffectationLazyRoute = AffectationLazyImport.update({
  path: '/affectation',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/affectation.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/affectation': {
      preLoaderRoute: typeof AffectationLazyImport
      parentRoute: typeof rootRoute
    }
    '/places': {
      preLoaderRoute: typeof PlacesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AffectationLazyRoute,
  PlacesLazyRoute,
])

/* prettier-ignore-end */
